version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/alpha"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/beta"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/studio"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "@sanity/base"
      - dependency-name: "@sanity/core"
      - dependency-name: "@sanity/default-layout"
      - dependency-name: "@sanity/default-login"
      - dependency-name: "@sanity/desk-tool"
      - dependency-name: "@sanity/vision"
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "monthly"
